server:
  port: 2448
spring:
  application:
    name: ReadArticlesServer
  datasource:
    url: jdbc:sqlite:./src/main/resources/db/server.db
    driverClassName: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
#    properties:
#      hibernate:
#        cache:
#          use_second_level_cache: true
#          region:
#            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  data:
    jdbc:
      repositories:
        enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_mail
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    cache-names: VerificationCodes
    type: caffeine
    caffeine:
      spec: expireAfterWrite=1m
  flyway:
    enabled: true
    locations: classpath:db/migration
    datasource:
      url: jdbc:sqlite:./src/main/resources/db/server.db
      driverClassName: org.sqlite.JDBC
logging:
  level:
    com:
      inkronsane:
        ReadArticlesServer: ERROR
#    root: warn
